"use strict";
const multiplica = (num1, num2) => num1 * num2;
let numero1 = 10;
let numero2 = 10;
const resultadoMultiplicacao = multiplica(numero1, numero2);
console.log(`Resultado: ${numero1} * ${numero2} = ${resultadoMultiplicacao}`);
let meuNome = "Franco";
const saudacao = (meuNome) => `Ola ${meuNome}`;
const minhaSaudacao = saudacao(meuNome);
console.log(minhaSaudacao);
